### ISSUE TITLE
what then?

### ISSUE THREAD

**Issue by T0xicivy** [tiagosh/AltcoinGenerator#16]
well, after i created the bootstrap with this script then what should i do to be able to lunch my coin?

**Comment by tiagosh** [comment]
You have to manually adjust the checkpoints, seeds, pictures and so on.
I don't have a full list of requirements because I never launched any coin for real. I created the script to actually learn more about generating genesis blocks, and in the end it became an altcoin generator.
If you find more items to change than the ones I mentioned, we could create a checklist somewhere in the README file. Any contribution is welcome.
Thanks.
