### ISSUE TITLE
Library erorr.

### ISSUE THREAD

**Issue by feloham** [tiagosh/AltcoinGenerator#33]
Hi it installed successfully. 
Then I went to mycoin/src
And wrote : 
./mycoind

It produced error : error while loading shared libraries: libboost_system.so.1.58.0:
 cannot open shared object file: No such file or directory

I'm using Ubuntu 14.04

**Comment by feloham** [comment]
Bump

**Comment by tiagosh** [comment]
To run the nodes you need to do exactly what it described in the README file: bash altcoin_generator.sh start
The problem is that you are trying to run in your host machine a binary that was compiled in the container, which is ubuntu 16.04. The script will launch the nodes in the containers.
If you wish to run a node in your host machine, you have to recompile everything manually.

**Comment by feloham** [comment]
Does it mean , it can't be done automatically in host like Google cloud? Yes I did exactly what you wrote , and I tried both ubuntu 14.04 and 16.04 . Same for both
