### ISSUE TITLE
Bad Substitution

### ISSUE THREAD

**Issue by odomojuli** [tiagosh/AltcoinGenerator#7]
altcoin_generator.sh: line 37: ${COIN_NAME,}: bad substitution
altcoin_generator.sh: line 38: ${COIN_NAME^}: bad substitution

**Comment by tiagosh** [comment]
Did you edit the script? The substitution don't seem to match what's in the master branch.

COIN_NAME_LOWER=${COIN_NAME,,}
COIN_NAME_UPPER=${COIN_NAME^^}

Also, check if the COIN_NAME variable isn't empty.

**Comment by wartimekillers** [comment]
altcoin_generator.sh: line 37: ${COIN_NAME,,}: bad substitution
altcoin_generator.sh: line 38: ${COIN_NAME^^}: bad substitution

have this problems too

**Comment by tiagosh** [comment]
@wartimekillers @odomojuli Are you both on linux? And what bash version are you using?

**Comment by tiagosh** [comment]
Hi, I just added support for macos. It works with standard bash 3.2 now.
Although it seemed to work fine before with newer bash, the script was failing to use sed, because it's not gnu sed.
Please update the script from git and try again. It should work out of the box now, but you have to first install gnu-sed: brew install gnu-sed

Let me know if that works.
Thanks.

**Comment by tiagosh** [comment]
Closing as it seems last version fixed the issue.
